<?PHP
	session_start();
	session_cache_expire(30);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
	<head>
		<title>
			Edit Crew
		</title>
		<link rel="stylesheet" href="styles.css" type="text/css" />
	</head>
	<body>
		<div id="container">
			<?PHP include('header.php');?>
			<div id="content">
				<?php
				include_once('database/dbCrews.php');
				include_once('database/dbPersons.php');
				include_once('database/dbSCL.php');
				include_once('database/dbLog.php');
				include_once('editCrew.inc');
					
				$crewid=$_GET['id'];
				$group = substr($crewid,9);
				if($crewid=="") {
					echo "<p>No Crew ID Supplied.  Click on \"Calendar\" above to edit crews.</p>";
				}
				else {
						$crew=select_dbCrews($crewid);
						if(!$crew instanceof Crew)
							echo "<p>Invalid Crew ID Supplied.  Click on \"Calendar\" above to edit crews.</p>";
						else {
							if(!process_fill_vacancy($_POST,$crew,$group) &&
							   !process_add_volunteer($_POST,$crew,$group)){
								if (process_unfill_crew($_POST,$crew,$group))
									$crew=select_dbCrews($crewid);
								else if (process_add_slot($_POST,$crew,$group))
									$crew=select_dbCrews($crewid);
								else if (process_clear_crew($_POST,$crew,$group))
								    $crew = select_dbCrews($crewid);
								else if (process_ignore_slot($_POST,$crew,$group))
									$crew=select_dbCrews($crewid);
								$persons=$crew->get_persons();
								echo "<br><br><table align=\"center\" border=\"1px\"><tr><td align=\"center\" colspan=\"2\"><b>"
									.get_crew_name_from_id($crewid)."</b></td></tr>";
								if($_SESSION['access_level']>=2) {
									echo "<tr><td valign=\"top\"><br>&nbsp;".do_slot_num($crew->get_slots())."</td><td>";
								
										echo ("<form method=\"POST\" style=\"margin-bottom:0;\">
											<input type=\"hidden\" name=\"_submit_add_slot\" value=\"1\"><br>
											<input type=\"submit\" value=\"Add Slot\" style=\"width: 150px\"
											name=\"submit\" >
											</form>");
										echo ("<form method=\"POST\" style=\"margin-bottom:0;\">
											<input type=\"hidden\" name=\"_submit_clear_crew\" value=\"1\">
											<input type=\"submit\" value=\"Clear Entire Crew\" style=\"width: 150px\"
											name=\"submit\" >
											</form>");
									echo "<br></td></tr>";
								}
								
							    echo display_filled_slots($persons);
								echo display_vacant_slots($crew->num_vacancies());
								echo "</td></tr></table>";
								echo "<p align=\"center\"><a href=\"calendar.php?month=".substr($crewid,0,5)."&group=".$group."&edit=true"."\">
									Back to Calendar</a>";
							}
						}
				}
				?>
				
			</div>
			<?PHP include('footer.inc');?>
		</div>
	</body>
</html>