<!-- Begin Footer -->
<br /><br />
<div align="center">
    <div align="center" style="border:dashed 1px #999; width:80%;">

        <p style="font-size:xx-small" class="footer-text">Copyright &copy; 2013 by Brian Jacobel, Simon Brooks, Oliver Fisher, and Allen Tucker.  
            <i>Homebase</i> is free open source software and it comes with absolutely no warranty.  
            You can redistribute and/or modify this software under the terms of the
            <a href="http://www.gnu.org/licenses/gpl.html" target="_BLANK"> GNU General Public License</a>.
        </p>
    </div>
</div>
<!-- End Footer -->