<?PHP
 /*
 * Copyright 2013 by Brian Jacobel, Oliver Fisher, Simon Brooks and Allen Tucker.
 * This program is part of RMH Homebase, which is free software.  It comes with 
 * absolutely no warranty. You can redistribute and/or modify it under the terms 
 * of the GNU General Public License as published by the Free Software Foundation
 * (see <http://www.gnu.org/licenses/ for more information).

 * Based on previous work by Johnny Coster, Judy Yang, Jackson Moniaga, Oliver Radwan, 
 * Maxwell Palmer, Nolan McNair, Taylor Talmage, and Allen Tucker. 
 */
session_start();
session_cache_expire(30);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
    <head>
        <title>
            RMH Homebase
        </title>
        <link rel="stylesheet" href="styles.css" type="text/css" />
    </head>
    <body>
        <div id="container">
            <?PHP include('header.php'); ?>
            <div id="content">
                <?PHP
                include_once('database/dbPersons.php');
                include_once('domain/Person.php');
                include_once('database/dbLog.php');
                include_once('domain/Crew.php');
                include_once('database/dbCrews.php');
                if ($_SESSION['_id'] != "guest") {
                    $person = retrieve_person($_SESSION['_id']);
                    echo "<p>Welcome, " . $person->get_first_name() . ", to Homebase!";
                }
                else
                    echo "<p>Welcome to Homebase!";
                $today = time();
                echo "   Today is " . date('l F j, Y', $today) . ".<p>";
                ?>

                <!-- your main page data goes here. This is the place to enter content -->
                <p>
                    <?PHP
                    if ($_SESSION['access_level'] == 1)
                        echo('<p>
							This is your personal homepage:
							your upcoming scheduled crews will always be posted here.
						');
                    ?>

                    <br>If you just want an overview of Homebase, select <a href="<?php echo($path); ?>dataSearch.php">about</a>.
                    <?PHP
                    if ($person)
                        echo ('<p>If you want to learn the details of using Homebase, select <a href="' . $path . 'help.php">help</a>.');
                    ?>
                    </ul>
                <p>	When you are finished, please remember to <a href="<?php echo($path); ?>logout.php">logout</a>.</li>

                    <?PHP
                    if ($person) {
                        /*
                         * Check type of person, and display home page based on that.
                         * all: password check
                         * guests: show link to application form
                         * applicants: show status of application form
                         * Volunteers, subs: show upcoming schedule
                         * Staff: show vacancies, birthdays, anniversaries, applicants
                         */

                        //DEFAULT PASSWORD CHECK
                        if (md5($person->get_id()) == $person->get_password()) {
                            if (!isset($_POST['_rp_submitted']))
                                echo('<div class="warning"><form method="post"><p><strong>We recommend that you change your password, which is currently default.</strong><table class="warningTable"><tr><td class="warningTable">Old Password:</td><td class="warningTable"><input type="password" name="_rp_old"></td></tr><tr><td class="warningTable">New password</td><td class="warningTable"><input type="password" name="_rp_newa"></td></tr><tr><td class="warningTable">New password<br />(confirm)</td><td class="warningTable"><input type="password" name="_rp_newb"></td></tr><tr><td colspan="2" align="right" class="warningTable"><input type="hidden" name="_rp_submitted" value="1"><input type="submit" value="Change Password"></td></tr></table></p></form></div>');
                            else {
                                //they've submitted
                                if (($_POST['_rp_newa'] != $_POST['_rp_newb']) || (!$_POST['_rp_newa']))
                                    echo('<div class="warning"><form method="post"><p>Error with new password. Ensure passwords match.</p><br /><table class="warningTable"><tr><td class="warningTable">Old Password:</td><td class="warningTable"><input type="password" name="_rp_old"></td></tr><tr><td class="warningTable">New password</td><td class="warningTable"><input type="password" name="_rp_newa"></td></tr><tr><td class="warningTable">New password<br />(confirm)</td><td class="warningTable"><input type="password" name="_rp_newb"></td></tr><tr><td colspan="2" align="center" class="warningTable"><input type="hidden" name="_rp_submitted" value="1"><input type="submit" value="Change Password"></form></td></tr></table></div>');
                                else if (md5($_POST['_rp_old']) != $person->get_password())
                                    echo('<div class="warning"><form method="post"><p>Error with old password.</p><br /><table class="warningTable"><tr><td class="warningTable">Old Password:</td><td class="warningTable"><input type="password" name="_rp_old"></td></tr><tr><td class="warningTable">New password</td><td class="warningTable"><input type="password" name="_rp_newa"></td></tr><tr><td class="warningTable">New password<br />(confirm)</td><td class="warningTable"><input type="password" name="_rp_newb"></td></tr><tr><td colspan="2" align="center" class="warningTable"><input type="hidden" name="_rp_submitted" value="1"><input type="submit" value="Change Password"></form></td></tr></table></div>');
                                else if ((md5($_POST['_rp_old']) == $person->get_password()) && ($_POST['_rp_newa'] == $_POST['_rp_newb'])) {
                                    $newPass = md5($_POST['_rp_newa']);
                                    change_password($person->get_id(), $newPass);
                                }
                            }
                            echo('<br clear="all">');
                        }

                        //NOTES OUTPUT
                        echo('<div class="infobox"><p class="notes"><strong>Notes from Operations Manager:</strong><br />');
                        echo($person->get_notes() . '</p></div><br>');

                        //APPLICANT CHECK
                        if ($person->get_first_name() != 'guest' && $person->get_status() == 'applicant') {
                            //SHOW STATUS
                            echo('<div class="infobox"><p><strong>Your application has been filed.</strong><br><br /><table><tr><td><strong>Step</strong></td><td><strong>Completed?</strong></td></tr><tr><td>Background Check</td><td>' . $person['background_check'] . '</td></tr><tr><td>Interview</td><td>' . $person['interview'] . '</td></tr><tr><td>Shadow</td><td>' . $person['shadow'] . '</td></tr></table></p></div>');
                        }

                        //VOLUNTEER CHECK
                        if ($_SESSION['access_level'] == 1) {
                            //we need to populate their schedule.
                            $crews = selectScheduled_dbCrews($person->get_id());

                            $scheduled_crews = array();
                            foreach ($crews as $crew) {
                                $crew_month = get_crew_month($crew);
                                $crew_day = get_crew_day($crew);
                                $crew_year = get_crew_year($crew);

                                //$crew_time_s = get_crew_start($crew);
                                //$crew_time_e = get_crew_end($crew);

                                $cur_month = date("m");
                                $cur_day = date("d");
                                $cur_year = date("y");

                                if ($crew_year > $cur_year)
                                    $upcoming_crews[] = $crew;
                                else if ($crew_year == $cur_year) {
                                    if ($cur_month < $crew_month)
                                        $upcoming_crews[] = $crew;
                                    else if ($crew_month == $cur_month) {
                                        if ($cur_day <= $crew_day) {
                                            $upcoming_crews[] = $crew;
                                        }
                                    }
                                }
                            }
                            if ($upcoming_crews) {
                                echo('<div class="scheduleBox"><p><strong>Your Upcoming Schedule:</strong><br /></p><ul>');
                                foreach ($upcoming_crews as $tableId) {
                                    echo('<li type="circle">' . get_crew_name_from_id($tableId)) . '</li>';
                                }
                                echo('</ul><p>If you need to cancel an upcoming crew, please contact House Manager (207-980-6282 or <a href="mailto:housemgr@rmhportland.org>">housemgr@rmhportland.org</a>).</p></div>');
                            }
                        }

                        if ($_SESSION['access_level'] == 2) {
                            //We have a manager authenticated
                            //log box

                            echo('<div class="logBox"><p><strong>Recent Schedule Changes:</strong><br />');
                            echo('<table class="searchResults">');
                            echo('<tr><td class="searchResults"><u>Time</u></td><td class="searchResults"><u>Message</u></td></tr>');
                            $log = get_last_log_entries(5);
                            for ($i = 4; $i >= 0; --$i) {
                                echo('<tr><td class="searchResults">' . $log[$i][1] . '</td>' .
                                '<td class="searchResults">' . $log[$i][2] . '</td></tr>');
                            }
                            echo ('</table><br><a href="' . $path . 'log.php">View full log</a></p></div><br>');

                            //beginning of vacancy box
                            //For checking time
                            $today = mktime(0, 0, 0, date('m'), date('d'), date('y'));
                            $two_weeks = $today + 14 * 86400;
							$today_id = date("y-m-d");
							$two_weeks_id = date("y-m-d",$two_weeks);
                            connect();
                            $vacancy_query = "SELECT id,slots,persons FROM dbCrews " .
                                    "WHERE id > '".$today_id."' AND id <= '".$two_weeks_id."' ORDER BY id;";
                            $vacancy_list = mysql_query($vacancy_query);
                            if (!$vacancy_list)
                                echo mysql_error();
                            //upcoming vacancies
                            if (mysql_num_rows($vacancy_list) > 0) {

                                echo('<div class="vacancyBox">');
                                echo('<p><strong>Upcoming Vacancies (next two weeks):</strong><ul>');
                                while ($thisRow = mysql_fetch_array($vacancy_list, MYSQL_ASSOC)) {
                                    $vacancies = $thisRow['slots'] - sizeof(explode(',',$thisRow['persons']));
                                    if ($vacancies > 0) {
                                        echo('<li type="circle"><a href="' . $path . 'editCrew.php?id=' . $thisRow['id'] . '">' . get_crew_name_from_id($thisRow['id']) . '</a></li>');
                                    }
                                }
                                echo('</ul></p></div><br>');
                            }
                            
                        // active volunteers who haven't worked recently
                            $everyone = getall_names("active", "volunteer");
                            if ($everyone && mysql_num_rows($everyone) > 0) {
                                //active volunteers who haven't worked for the last two months
                                $two_months_ago = $today - 60 * 86400;
                                echo('<div class="inactiveBox">');
                                echo('<p><strong>Unscheduled active house volunteers who haven\'t worked during the last two months:</strong>');
                                echo('<table class="searchResults"><tr><td class="searchResults"><u>Name</u></td><td class="searchResults"><u>Date Last Worked</u></td></tr>');
                                while ($thisRow = mysql_fetch_array($everyone, MYSQL_ASSOC)) {
                                    if (!preg_match("/manager/", $thisRow['type'])) {
                                        $crews = selectScheduled_dbCrews($thisRow['id']);
                                        $havent_worked = true;
                                        $last_worked = "";
                                        for ($i = 0; $i < count($crews) && $havent_worked; $i++) {
                                            $date_worked = mktime(0, 0, 0, get_crew_month($crews[$i]), get_crew_day($crews[$i]), get_crew_year($crews[$i]));
                                            $last_worked = substr($crews[$i], 0, 8);
                                            if ($date_worked > $two_months_ago) 
                                                $havent_worked = false;
                                        }
                                        if ($havent_worked)
                                            echo('<tr><td class="searchResults"><a href="personEdit.php?id=' . $thisRow['id'] . '">' . $thisRow['first_name'] . ' ' . $thisRow['last_name'] . '</a></td><td class="searchResults">' . $last_worked . '</td></tr>');
                                    }
                                }
                                echo('</table></p></div><br>');
                            }
                            
                            
                        }
                    }
                    ?>
                    </div>
                    <?PHP include('footer.inc'); ?>
        </div>
    </body>
</html>